import CasDslTests.Core
import CasDslTests.Denote
import CasDslTests.Membership
import CasDslTests.Wording
import CasDslTests.Codec
import CasDslTests.Latex
import CasDslTests.Std
import CasDslTests.Eval
import CasDslTests.Extension
import CasDslTests.Transport
import CasDslTests.CanonicalMaps
