/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import CasCatalogue.Leaves.Foundation.Subsets
public import LeanCategories.Algebra.Concrete.MatrixElements
public import LeanCategories.Foundation.SetOperations
public import LeanCategories.Analytic.Points
public import LeanCategories.Schemes.OverRationals
public meta import CasCatalogue.Registry.Extension
public meta import CasCatalogue.ConstructorCatalogue
public meta import CasCatalogue.Leaves.Foundation.Subsets

@[expose] public section

/-!
# Elements of structured objects, sets, and function spaces (`cc-dsl-migration`)

The categories, structural functors and methods of the notebook surface's element-level
universe, registered from `lean-categories` (`LeanCategories.Foundation.IsoElements`,
`…Algebra.Concrete.{Ring,Polynomial,Matrix}Elements`, `…Foundation.SetOperations`,
`…Analytic.Points`, `…Schemes.OverRationals`):

* points of classes of rings (euclidean ⊆ PID ⊆ UFD ⊆ commutative rings), of polynomial rings
  and matrix rings, with the structural functors between them (inclusions of classes; `K[X]` is
  euclidean, `R[X]` is a UFD over a UFD);
* enumerations, finite enumerated subsets (over rings: `sum`, `prod`), multisets;
* points of `ℂ`, `ℝ`, and of function spaces;
* the value categories of the methods (categories of elements of the value functors).

Each method row names the functor whose object map is the operation (Mathlib's function, or the
set of admissible answers where the answer is a choice). This module is generated from one table;
it holds registrations only (generated by `scripts/gen_elements_catalogue.py`).
-/

open CategoryTheory

namespace CasCatalogue

namespace CategoryId
def ringPoints : CategoryId := ⟨"cat.ring_points"⟩
def ufdPoints : CategoryId := ⟨"cat.ufd_points"⟩
def pidPoints : CategoryId := ⟨"cat.pid_points"⟩
def euclideanPoints : CategoryId := ⟨"cat.euclidean_points"⟩
def polyPoints : CategoryId := ⟨"cat.poly_points"⟩
def domainPolyPoints : CategoryId := ⟨"cat.domain_poly_points"⟩
def ufdPolyPoints : CategoryId := ⟨"cat.ufd_poly_points"⟩
def fieldPolyPoints : CategoryId := ⟨"cat.field_poly_points"⟩
def matrixPoints : CategoryId := ⟨"cat.matrix_points"⟩
def enumerations : CategoryId := ⟨"cat.enumerations"⟩
def finiteLists : CategoryId := ⟨"cat.finite_lists"⟩
def ringFiniteLists : CategoryId := ⟨"cat.ring_finite_lists"⟩
def multisetPoints : CategoryId := ⟨"cat.multiset_points"⟩
def complexPoints : CategoryId := ⟨"cat.complex_points"⟩
def realPoints : CategoryId := ⟨"cat.real_points"⟩
def functionPoints : CategoryId := ⟨"cat.function_points"⟩
def realFunctionPoints : CategoryId := ⟨"cat.real_function_points"⟩
def schemesOverQ : CategoryId := ⟨"cat.schemes_over_q"⟩
def factorizations : CategoryId := ⟨"cat.values.factorizations"⟩
def gcdValues : CategoryId := ⟨"cat.values.gcds"⟩
def propositions : CategoryId := ⟨"cat.values.propositions"⟩
def polyValues : CategoryId := ⟨"cat.values.polynomials"⟩
def polySetValues : CategoryId := ⟨"cat.values.polynomial_sets"⟩
def degrees : CategoryId := ⟨"cat.values.degrees"⟩
def matrixSetValues : CategoryId := ⟨"cat.values.matrix_sets"⟩
def rootValues : CategoryId := ⟨"cat.values.roots"⟩
def ringValues : CategoryId := ⟨"cat.values.ring_elements"⟩
def naturals : CategoryId := ⟨"cat.values.naturals"⟩
def vectorSetValues : CategoryId := ⟨"cat.values.vector_sets"⟩
def subsetOperations : CategoryId := ⟨"cat.values.subset_operations"⟩
def sequenceValues : CategoryId := ⟨"cat.values.sequences"⟩
def pointPredicateValues : CategoryId := ⟨"cat.values.point_predicates"⟩
def subsetPredicateValues : CategoryId := ⟨"cat.values.subset_predicates"⟩
def approximationValues : CategoryId := ⟨"cat.values.approximations"⟩
def limitValues : CategoryId := ⟨"cat.values.limits"⟩
def integralValues : CategoryId := ⟨"cat.values.integrals"⟩
def taylorValues : CategoryId := ⟨"cat.values.taylor"⟩
end CategoryId

namespace FunctorId
def euclideanToPid : FunctorId := ⟨"fun.euclidean_points.pid"⟩
def pidToUfd : FunctorId := ⟨"fun.pid_points.ufd"⟩
def ufdToRing : FunctorId := ⟨"fun.ufd_points.ring"⟩
def domainPolyToPoly : FunctorId := ⟨"fun.domain_poly_points.poly"⟩
def ufdPolyToDomainPoly : FunctorId := ⟨"fun.ufd_poly_points.domain_poly"⟩
def ufdPolyToUfd : FunctorId := ⟨"fun.ufd_poly_points.ufd_points"⟩
def fieldPolyToDomainPoly : FunctorId := ⟨"fun.field_poly_points.domain_poly"⟩
def fieldPolyToEuclidean : FunctorId := ⟨"fun.field_poly_points.euclidean_points"⟩
def finiteListsToEnumerations : FunctorId := ⟨"fun.finite_lists.enumeration"⟩
def enumerationsToSubsets : FunctorId := ⟨"fun.enumerations.subset"⟩
def ringFiniteListsForget : FunctorId := ⟨"fun.ring_finite_lists.forget"⟩
def realToComplex : FunctorId := ⟨"fun.real_points.complex"⟩
def realFunctionToFunction : FunctorId := ⟨"fun.real_function_points.function"⟩
def factor : FunctorId := ⟨"fun.ufd_points.factor"⟩
def gcd : FunctorId := ⟨"fun.ufd_points.gcd"⟩
def isPrime : FunctorId := ⟨"fun.ufd_points.is_prime"⟩
def derivative : FunctorId := ⟨"fun.poly_points.derivative"⟩
def antiderivative : FunctorId := ⟨"fun.poly_points.antiderivative"⟩
def deg : FunctorId := ⟨"fun.poly_points.deg"⟩
def companion : FunctorId := ⟨"fun.poly_points.companion_matrix"⟩
def roots : FunctorId := ⟨"fun.domain_poly_points.roots"⟩
def det : FunctorId := ⟨"fun.matrix_points.det"⟩
def trace : FunctorId := ⟨"fun.matrix_points.trace"⟩
def charpoly : FunctorId := ⟨"fun.matrix_points.charpoly"⟩
def inverse : FunctorId := ⟨"fun.matrix_points.inverse"⟩
def matrixRank : FunctorId := ⟨"fun.matrix_points.rank"⟩
def matrixKer : FunctorId := ⟨"fun.matrix_points.ker"⟩
def union : FunctorId := ⟨"fun.subsets.union"⟩
def intersect : FunctorId := ⟨"fun.subsets.intersect"⟩
def diff : FunctorId := ⟨"fun.subsets.diff"⟩
def symdiff : FunctorId := ⟨"fun.subsets.symdiff"⟩
def subset : FunctorId := ⟨"fun.subsets.subset"⟩
def nth : FunctorId := ⟨"fun.enumerations.nth"⟩
def sum : FunctorId := ⟨"fun.ring_finite_lists.sum"⟩
def prod : FunctorId := ⟨"fun.ring_finite_lists.prod"⟩
def multisetContains : FunctorId := ⟨"fun.multiset_points.contains"⟩
def multisetCard : FunctorId := ⟨"fun.multiset_points.cardinality"⟩
def multisetEquals : FunctorId := ⟨"fun.multiset_points.set_eq"⟩
def multisetSubset : FunctorId := ⟨"fun.multiset_points.subset"⟩
def re : FunctorId := ⟨"fun.complex_points.re"⟩
def im : FunctorId := ⟨"fun.complex_points.im"⟩
def bar : FunctorId := ⟨"fun.complex_points.bar"⟩
def abs : FunctorId := ⟨"fun.complex_points.abs"⟩
def approximate : FunctorId := ⟨"fun.complex_points.approximate"⟩
def image : FunctorId := ⟨"fun.function_points.image"⟩
def limit : FunctorId := ⟨"fun.real_function_points.limit"⟩
def integral : FunctorId := ⟨"fun.real_function_points.definite_integral"⟩
def taylor : FunctorId := ⟨"fun.real_function_points.taylor_expansion"⟩
end FunctorId

namespace Elements

def RingPoints : CategoryExpr := .atom CategoryId.ringPoints
def UfdPoints : CategoryExpr := .atom CategoryId.ufdPoints
def PidPoints : CategoryExpr := .atom CategoryId.pidPoints
def EuclideanPoints : CategoryExpr := .atom CategoryId.euclideanPoints
def PolyPoints : CategoryExpr := .atom CategoryId.polyPoints
def DomainPolyPoints : CategoryExpr := .atom CategoryId.domainPolyPoints
def UfdPolyPoints : CategoryExpr := .atom CategoryId.ufdPolyPoints
def FieldPolyPoints : CategoryExpr := .atom CategoryId.fieldPolyPoints
def MatrixPoints : CategoryExpr := .atom CategoryId.matrixPoints
def Enumerations : CategoryExpr := .atom CategoryId.enumerations
def FiniteLists : CategoryExpr := .atom CategoryId.finiteLists
def RingFiniteLists : CategoryExpr := .atom CategoryId.ringFiniteLists
def MultisetPoints : CategoryExpr := .atom CategoryId.multisetPoints
def ComplexPoints : CategoryExpr := .atom CategoryId.complexPoints
def RealPoints : CategoryExpr := .atom CategoryId.realPoints
def FunctionPoints : CategoryExpr := .atom CategoryId.functionPoints
def RealFunctionPoints : CategoryExpr := .atom CategoryId.realFunctionPoints
def SchemesOverQ : CategoryExpr := .atom CategoryId.schemesOverQ
def Factorizations : CategoryExpr := .atom CategoryId.factorizations
def GcdValues : CategoryExpr := .atom CategoryId.gcdValues
def Propositions : CategoryExpr := .atom CategoryId.propositions
def PolyValues : CategoryExpr := .atom CategoryId.polyValues
def PolySetValues : CategoryExpr := .atom CategoryId.polySetValues
def Degrees : CategoryExpr := .atom CategoryId.degrees
def MatrixSetValues : CategoryExpr := .atom CategoryId.matrixSetValues
def RootValues : CategoryExpr := .atom CategoryId.rootValues
def RingValues : CategoryExpr := .atom CategoryId.ringValues
def Naturals : CategoryExpr := .atom CategoryId.naturals
def VectorSetValues : CategoryExpr := .atom CategoryId.vectorSetValues
def SubsetOperations : CategoryExpr := .atom CategoryId.subsetOperations
def SequenceValues : CategoryExpr := .atom CategoryId.sequenceValues
def PointPredicateValues : CategoryExpr := .atom CategoryId.pointPredicateValues
def SubsetPredicateValues : CategoryExpr := .atom CategoryId.subsetPredicateValues
def ApproximationValues : CategoryExpr := .atom CategoryId.approximationValues
def LimitValues : CategoryExpr := .atom CategoryId.limitValues
def IntegralValues : CategoryExpr := .atom CategoryId.integralValues
def TaylorValues : CategoryExpr := .atom CategoryId.taylorValues
def EuclideanToPidExpr : FunctorExpr EuclideanPoints PidPoints := .atomic FunctorId.euclideanToPid
def PidToUfdExpr : FunctorExpr PidPoints UfdPoints := .atomic FunctorId.pidToUfd
def UfdToRingExpr : FunctorExpr UfdPoints RingPoints := .atomic FunctorId.ufdToRing
def DomainPolyToPolyExpr : FunctorExpr DomainPolyPoints PolyPoints := .atomic FunctorId.domainPolyToPoly
def UfdPolyToDomainPolyExpr : FunctorExpr UfdPolyPoints DomainPolyPoints := .atomic FunctorId.ufdPolyToDomainPoly
def UfdPolyToUfdExpr : FunctorExpr UfdPolyPoints UfdPoints := .atomic FunctorId.ufdPolyToUfd
def FieldPolyToDomainPolyExpr : FunctorExpr FieldPolyPoints DomainPolyPoints := .atomic FunctorId.fieldPolyToDomainPoly
def FieldPolyToEuclideanExpr : FunctorExpr FieldPolyPoints EuclideanPoints := .atomic FunctorId.fieldPolyToEuclidean
def FiniteListsToEnumerationsExpr : FunctorExpr FiniteLists Enumerations := .atomic FunctorId.finiteListsToEnumerations
def EnumerationsToSubsetsExpr : FunctorExpr Enumerations Constructed.SubobjectsSets := .atomic FunctorId.enumerationsToSubsets
def RingFiniteListsForgetExpr : FunctorExpr RingFiniteLists FiniteLists := .atomic FunctorId.ringFiniteListsForget
def RealToComplexExpr : FunctorExpr RealPoints ComplexPoints := .atomic FunctorId.realToComplex
def RealFunctionToFunctionExpr : FunctorExpr RealFunctionPoints FunctionPoints := .atomic FunctorId.realFunctionToFunction
def FactorExpr : FunctorExpr UfdPoints Factorizations := .atomic FunctorId.factor
def GcdExpr : FunctorExpr UfdPoints GcdValues := .atomic FunctorId.gcd
def IsPrimeExpr : FunctorExpr UfdPoints Propositions := .atomic FunctorId.isPrime
def DerivativeExpr : FunctorExpr PolyPoints PolyValues := .atomic FunctorId.derivative
def AntiderivativeExpr : FunctorExpr PolyPoints PolySetValues := .atomic FunctorId.antiderivative
def DegExpr : FunctorExpr PolyPoints Degrees := .atomic FunctorId.deg
def CompanionExpr : FunctorExpr PolyPoints MatrixSetValues := .atomic FunctorId.companion
def RootsExpr : FunctorExpr DomainPolyPoints RootValues := .atomic FunctorId.roots
def DetExpr : FunctorExpr MatrixPoints RingValues := .atomic FunctorId.det
def TraceExpr : FunctorExpr MatrixPoints RingValues := .atomic FunctorId.trace
def CharpolyExpr : FunctorExpr MatrixPoints PolyValues := .atomic FunctorId.charpoly
def InverseExpr : FunctorExpr MatrixPoints MatrixSetValues := .atomic FunctorId.inverse
def MatrixRankExpr : FunctorExpr MatrixPoints Naturals := .atomic FunctorId.matrixRank
def MatrixKerExpr : FunctorExpr MatrixPoints VectorSetValues := .atomic FunctorId.matrixKer
def UnionExpr : FunctorExpr Foundation.Subsets.CoreSubobjectsSets SubsetOperations := .atomic FunctorId.union
def IntersectExpr : FunctorExpr Foundation.Subsets.CoreSubobjectsSets SubsetOperations := .atomic FunctorId.intersect
def DiffExpr : FunctorExpr Foundation.Subsets.CoreSubobjectsSets SubsetOperations := .atomic FunctorId.diff
def SymdiffExpr : FunctorExpr Foundation.Subsets.CoreSubobjectsSets SubsetOperations := .atomic FunctorId.symdiff
def SubsetExpr : FunctorExpr Foundation.Subsets.CoreSubobjectsSets Foundation.Subsets.SubsetPredicates := .atomic FunctorId.subset
def NthExpr : FunctorExpr Enumerations SequenceValues := .atomic FunctorId.nth
def SumExpr : FunctorExpr RingFiniteLists RingValues := .atomic FunctorId.sum
def ProdExpr : FunctorExpr RingFiniteLists RingValues := .atomic FunctorId.prod
def MultisetContainsExpr : FunctorExpr MultisetPoints PointPredicateValues := .atomic FunctorId.multisetContains
def MultisetCardExpr : FunctorExpr MultisetPoints Naturals := .atomic FunctorId.multisetCard
def MultisetEqualsExpr : FunctorExpr MultisetPoints SubsetPredicateValues := .atomic FunctorId.multisetEquals
def MultisetSubsetExpr : FunctorExpr MultisetPoints SubsetPredicateValues := .atomic FunctorId.multisetSubset
def ReExpr : FunctorExpr ComplexPoints RealPoints := .atomic FunctorId.re
def ImExpr : FunctorExpr ComplexPoints RealPoints := .atomic FunctorId.im
def BarExpr : FunctorExpr ComplexPoints ComplexPoints := .atomic FunctorId.bar
def AbsExpr : FunctorExpr ComplexPoints RealPoints := .atomic FunctorId.abs
def ApproximateExpr : FunctorExpr ComplexPoints ApproximationValues := .atomic FunctorId.approximate
def ImageExpr : FunctorExpr FunctionPoints Constructed.SubobjectsSets := .atomic FunctorId.image
def LimitExpr : FunctorExpr RealFunctionPoints LimitValues := .atomic FunctorId.limit
def IntegralExpr : FunctorExpr RealFunctionPoints IntegralValues := .atomic FunctorId.integral
def TaylorExpr : FunctorExpr RealFunctionPoints TaylorValues := .atomic FunctorId.taylor

noncomputable section

/-- The category of elements of commutative rings. -/
def ringPointsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Algebra.RingPoints.{0})
def ringPointsRealization : CategoryRealization RingPoints ringPointsCategory := {}
/-- The category of elements of unique factorization domains. -/
def ufdPointsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Algebra.UFDPoints.{0})
def ufdPointsRealization : CategoryRealization UfdPoints ufdPointsCategory := {}
/-- The category of elements of principal ideal domains. -/
def pidPointsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Algebra.PIDPoints.{0})
def pidPointsRealization : CategoryRealization PidPoints pidPointsCategory := {}
/-- The category of elements of euclidean domains. -/
def euclideanPointsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Algebra.EuclideanPoints.{0})
def euclideanPointsRealization : CategoryRealization EuclideanPoints euclideanPointsCategory := {}
/-- The category of polynomials over commutative rings. -/
def polyPointsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Algebra.PolyPoints.{0})
def polyPointsRealization : CategoryRealization PolyPoints polyPointsCategory := {}
/-- The category of polynomials over domains. -/
def domainPolyPointsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Algebra.DomainPolyPoints.{0})
def domainPolyPointsRealization : CategoryRealization DomainPolyPoints domainPolyPointsCategory := {}
/-- The category of polynomials over unique factorization domains. -/
def ufdPolyPointsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Algebra.UFDPolyPoints.{0})
def ufdPolyPointsRealization : CategoryRealization UfdPolyPoints ufdPolyPointsCategory := {}
/-- The category of polynomials over fields. -/
def fieldPolyPointsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Algebra.FieldPolyPoints.{0})
def fieldPolyPointsRealization : CategoryRealization FieldPolyPoints fieldPolyPointsCategory := {}
/-- The category of square matrices over commutative rings. -/
def matrixPointsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Algebra.MatrixPoints.{0})
def matrixPointsRealization : CategoryRealization MatrixPoints matrixPointsCategory := {}
/-- The category of sets with an order of their elements. -/
def enumerationsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Foundation.Enumerations.{0})
def enumerationsRealization : CategoryRealization Enumerations enumerationsCategory := {}
/-- The category of finite subsets presented as duplicate-free lists. -/
def finiteListsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Foundation.FiniteLists.{0})
def finiteListsRealization : CategoryRealization FiniteLists finiteListsCategory := {}
/-- The category of finite subsets of commutative rings. -/
def ringFiniteListsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Foundation.RingFiniteLists.{0})
def ringFiniteListsRealization : CategoryRealization RingFiniteLists ringFiniteListsCategory := {}
/-- The category of multisets. -/
def multisetPointsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Foundation.MultisetPoints.{0})
def multisetPointsRealization : CategoryRealization MultisetPoints multisetPointsCategory := {}
/-- The category of points of ℂ. -/
def complexPointsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Analytic.ComplexPoints)
def complexPointsRealization : CategoryRealization ComplexPoints complexPointsCategory := {}
/-- The category of points of ℝ. -/
def realPointsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Analytic.RealPoints)
def realPointsRealization : CategoryRealization RealPoints realPointsCategory := {}
/-- The category of functions between sets. -/
def functionPointsCategory : LeanCategories.ObjCat.{1, 1} := Cat.of (LeanCategories.Analytic.FunctionPoints.{0})
def functionPointsRealization : CategoryRealization FunctionPoints functionPointsCategory := {}
/-- The category of real functions. -/
def realFunctionPointsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Analytic.RealFunctionPoints)
def realFunctionPointsRealization : CategoryRealization RealFunctionPoints realFunctionPointsCategory := {}
/-- The category of schemes over ℚ. -/
def schemesOverQCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Schemes.SchemesOverRationals)
def schemesOverQRealization : CategoryRealization SchemesOverQ schemesOverQCategory := {}
/-- The category of sets of factorizations. -/
def factorizationsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Algebra.UFD.factorizationSets.{0}.Elements)
def factorizationsRealization : CategoryRealization Factorizations factorizationsCategory := {}
/-- The category of greatest common divisors. -/
def gcdValuesCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Algebra.UFD.gcdSets.{0}.Elements)
def gcdValuesRealization : CategoryRealization GcdValues gcdValuesCategory := {}
/-- The category of truth values. -/
def propositionsCategory : LeanCategories.ObjCat := Cat.of (Discrete Prop)
def propositionsRealization : CategoryRealization Propositions propositionsCategory := {}
/-- The category of polynomials. -/
def polyValuesCategory : LeanCategories.ObjCat := Cat.of ((Core.inclusion CommRingCat.{0} ⋙ LeanCategories.Algebra.polyCarrier.{0}).Elements)
def polyValuesRealization : CategoryRealization PolyValues polyValuesCategory := {}
/-- The category of sets of polynomials. -/
def polySetValuesCategory : LeanCategories.ObjCat := Cat.of ((Core.inclusion CommRingCat.{0} ⋙ LeanCategories.Algebra.polyCarrier.{0} ⋙ LeanCategories.Foundation.powersetFunctor).Elements)
def polySetValuesRealization : CategoryRealization PolySetValues polySetValuesCategory := {}
/-- The category of degrees. -/
def degreesCategory : LeanCategories.ObjCat := Cat.of (Discrete (WithBot ℕ))
def degreesRealization : CategoryRealization Degrees degreesCategory := {}
/-- The category of sets of square matrices. -/
def matrixSetValuesCategory : LeanCategories.ObjCat := Cat.of ((Core.inclusion CommRingCat.{0} ⋙ LeanCategories.Algebra.Poly.squareMatrices.{0} ⋙ LeanCategories.Foundation.powersetFunctor).Elements)
def matrixSetValuesRealization : CategoryRealization MatrixSetValues matrixSetValuesCategory := {}
/-- The category of multisets of roots. -/
def rootValuesCategory : LeanCategories.ObjCat := Cat.of ((Core.inclusion LeanCategories.Algebra.DomainCat.{0} ⋙ LeanCategories.Algebra.domainToCommRing ⋙ LeanCategories.Algebra.ringCarrier ⋙ LeanCategories.Foundation.multisetFunctor).Elements)
def rootValuesRealization : CategoryRealization RootValues rootValuesCategory := {}
/-- The category of ring elements. -/
def ringValuesCategory : LeanCategories.ObjCat := Cat.of ((Core.inclusion CommRingCat.{0} ⋙ LeanCategories.Algebra.ringCarrier.{0}).Elements)
def ringValuesRealization : CategoryRealization RingValues ringValuesCategory := {}
/-- The category of natural numbers. -/
def naturalsCategory : LeanCategories.ObjCat := Cat.of (Discrete ℕ)
def naturalsRealization : CategoryRealization Naturals naturalsCategory := {}
/-- The category of sets of vectors. -/
def vectorSetValuesCategory : LeanCategories.ObjCat := Cat.of ((Core.inclusion CommRingCat.{0} ⋙ LeanCategories.Algebra.Mat.vectors.{0} ⋙ LeanCategories.Foundation.powersetFunctor).Elements)
def vectorSetValuesRealization : CategoryRealization VectorSetValues vectorSetValuesCategory := {}
/-- The category of operations on subsets. -/
def subsetOperationsCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Foundation.ambientSubsetOperations.{0}.Elements)
def subsetOperationsRealization : CategoryRealization SubsetOperations subsetOperationsCategory := {}
/-- The category of partial sequences. -/
def sequenceValuesCategory : LeanCategories.ObjCat := Cat.of ((Core.inclusion (Type) ⋙ LeanCategories.Foundation.seqFunctor.{0}).Elements)
def sequenceValuesRealization : CategoryRealization SequenceValues sequenceValuesCategory := {}
/-- The category of predicates on elements. -/
def pointPredicateValuesCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Foundation.pointPredicates.{0}.Elements)
def pointPredicateValuesRealization : CategoryRealization PointPredicateValues pointPredicateValuesCategory := {}
/-- The category of predicates on subsets. -/
def subsetPredicateValuesCategory : LeanCategories.ObjCat := Cat.of (LeanCategories.Foundation.subsetPredicates.{0}.Elements)
def subsetPredicateValuesRealization : CategoryRealization SubsetPredicateValues subsetPredicateValuesCategory := {}
/-- The category of sets of approximations. -/
def approximationValuesCategory : LeanCategories.ObjCat := Cat.of (Discrete (ℚ → Set (ℚ × ℚ)))
def approximationValuesRealization : CategoryRealization ApproximationValues approximationValuesCategory := {}
/-- The category of sets of limits. -/
def limitValuesCategory : LeanCategories.ObjCat := Cat.of (Discrete (EReal → Set EReal))
def limitValuesRealization : CategoryRealization LimitValues limitValuesCategory := {}
/-- The category of definite integrals. -/
def integralValuesCategory : LeanCategories.ObjCat := Cat.of (Discrete (ℝ → ℝ → ℝ))
def integralValuesRealization : CategoryRealization IntegralValues integralValuesCategory := {}
/-- The category of Taylor polynomials. -/
def taylorValuesCategory : LeanCategories.ObjCat := Cat.of (Discrete (ℕ → Polynomial ℝ))
def taylorValuesRealization : CategoryRealization TaylorValues taylorValuesCategory := {}
def euclideanToPidDeclaration : euclideanPointsCategory ⥤ pidPointsCategory := LeanCategories.Algebra.euclideanPointsToPID.{0}
def euclideanToPidRealization : FunctorRealization EuclideanToPidExpr euclideanPointsCategory pidPointsCategory euclideanToPidDeclaration :=
  { sourceRealization := euclideanPointsRealization, targetRealization := pidPointsRealization }
def pidToUfdDeclaration : pidPointsCategory ⥤ ufdPointsCategory := LeanCategories.Algebra.pidPointsToUFD.{0}
def pidToUfdRealization : FunctorRealization PidToUfdExpr pidPointsCategory ufdPointsCategory pidToUfdDeclaration :=
  { sourceRealization := pidPointsRealization, targetRealization := ufdPointsRealization }
def ufdToRingDeclaration : ufdPointsCategory ⥤ ringPointsCategory := LeanCategories.Algebra.ufdPointsToRing.{0}
def ufdToRingRealization : FunctorRealization UfdToRingExpr ufdPointsCategory ringPointsCategory ufdToRingDeclaration :=
  { sourceRealization := ufdPointsRealization, targetRealization := ringPointsRealization }
def domainPolyToPolyDeclaration : domainPolyPointsCategory ⥤ polyPointsCategory := LeanCategories.Algebra.domainPolyToPoly.{0}
def domainPolyToPolyRealization : FunctorRealization DomainPolyToPolyExpr domainPolyPointsCategory polyPointsCategory domainPolyToPolyDeclaration :=
  { sourceRealization := domainPolyPointsRealization, targetRealization := polyPointsRealization }
def ufdPolyToDomainPolyDeclaration : ufdPolyPointsCategory ⥤ domainPolyPointsCategory := LeanCategories.Algebra.ufdPolyToDomainPoly.{0}
def ufdPolyToDomainPolyRealization : FunctorRealization UfdPolyToDomainPolyExpr ufdPolyPointsCategory domainPolyPointsCategory ufdPolyToDomainPolyDeclaration :=
  { sourceRealization := ufdPolyPointsRealization, targetRealization := domainPolyPointsRealization }
def ufdPolyToUfdDeclaration : ufdPolyPointsCategory ⥤ ufdPointsCategory := LeanCategories.Algebra.ufdPolyToUFDPoints.{0}
def ufdPolyToUfdRealization : FunctorRealization UfdPolyToUfdExpr ufdPolyPointsCategory ufdPointsCategory ufdPolyToUfdDeclaration :=
  { sourceRealization := ufdPolyPointsRealization, targetRealization := ufdPointsRealization }
def fieldPolyToDomainPolyDeclaration : fieldPolyPointsCategory ⥤ domainPolyPointsCategory := LeanCategories.Algebra.fieldPolyToDomainPoly.{0}
def fieldPolyToDomainPolyRealization : FunctorRealization FieldPolyToDomainPolyExpr fieldPolyPointsCategory domainPolyPointsCategory fieldPolyToDomainPolyDeclaration :=
  { sourceRealization := fieldPolyPointsRealization, targetRealization := domainPolyPointsRealization }
def fieldPolyToEuclideanDeclaration : fieldPolyPointsCategory ⥤ euclideanPointsCategory := LeanCategories.Algebra.fieldPolyToEuclideanPoints.{0}
def fieldPolyToEuclideanRealization : FunctorRealization FieldPolyToEuclideanExpr fieldPolyPointsCategory euclideanPointsCategory fieldPolyToEuclideanDeclaration :=
  { sourceRealization := fieldPolyPointsRealization, targetRealization := euclideanPointsRealization }
def finiteListsToEnumerationsDeclaration : finiteListsCategory ⥤ enumerationsCategory := LeanCategories.Foundation.listSequence.{0}
def finiteListsToEnumerationsRealization : FunctorRealization FiniteListsToEnumerationsExpr finiteListsCategory enumerationsCategory finiteListsToEnumerationsDeclaration :=
  { sourceRealization := finiteListsRealization, targetRealization := enumerationsRealization }
def enumerationsToSubsetsDeclaration : enumerationsCategory ⥤ CasCatalogue.Catalogue.ConstructorRegistration.subobjectsSetsCategory.{0} := LeanCategories.Foundation.enumerationRange.{0}
def enumerationsToSubsetsRealization : FunctorRealization EnumerationsToSubsetsExpr enumerationsCategory CasCatalogue.Catalogue.ConstructorRegistration.subobjectsSetsCategory.{0} enumerationsToSubsetsDeclaration :=
  { sourceRealization := enumerationsRealization, targetRealization := CasCatalogue.Catalogue.ConstructorRegistration.subobjectsSetsRealization }
def ringFiniteListsForgetDeclaration : ringFiniteListsCategory ⥤ finiteListsCategory := LeanCategories.Foundation.ringFiniteListsForget.{0}
def ringFiniteListsForgetRealization : FunctorRealization RingFiniteListsForgetExpr ringFiniteListsCategory finiteListsCategory ringFiniteListsForgetDeclaration :=
  { sourceRealization := ringFiniteListsRealization, targetRealization := finiteListsRealization }
def realToComplexDeclaration : realPointsCategory ⥤ complexPointsCategory := LeanCategories.Analytic.realToComplex
def realToComplexRealization : FunctorRealization RealToComplexExpr realPointsCategory complexPointsCategory realToComplexDeclaration :=
  { sourceRealization := realPointsRealization, targetRealization := complexPointsRealization }
def realFunctionToFunctionDeclaration : realFunctionPointsCategory ⥤ functionPointsCategory := LeanCategories.Analytic.realFunctionToFunction
def realFunctionToFunctionRealization : FunctorRealization RealFunctionToFunctionExpr realFunctionPointsCategory functionPointsCategory realFunctionToFunctionDeclaration :=
  { sourceRealization := realFunctionPointsRealization, targetRealization := functionPointsRealization }
def factorDeclaration : ufdPointsCategory ⥤ factorizationsCategory := LeanCategories.Algebra.UFD.factor.{0}
def factorRealization : FunctorRealization FactorExpr ufdPointsCategory factorizationsCategory factorDeclaration :=
  { sourceRealization := ufdPointsRealization, targetRealization := factorizationsRealization }
def gcdDeclaration : ufdPointsCategory ⥤ gcdValuesCategory := LeanCategories.Algebra.UFD.gcd.{0}
def gcdRealization : FunctorRealization GcdExpr ufdPointsCategory gcdValuesCategory gcdDeclaration :=
  { sourceRealization := ufdPointsRealization, targetRealization := gcdValuesRealization }
def isPrimeDeclaration : ufdPointsCategory ⥤ propositionsCategory := LeanCategories.Algebra.UFD.isPrime.{0}
def isPrimeRealization : FunctorRealization IsPrimeExpr ufdPointsCategory propositionsCategory isPrimeDeclaration :=
  { sourceRealization := ufdPointsRealization, targetRealization := propositionsRealization }
def derivativeDeclaration : polyPointsCategory ⥤ polyValuesCategory := LeanCategories.Algebra.Poly.derivativeMethod.{0}
def derivativeRealization : FunctorRealization DerivativeExpr polyPointsCategory polyValuesCategory derivativeDeclaration :=
  { sourceRealization := polyPointsRealization, targetRealization := polyValuesRealization }
def antiderivativeDeclaration : polyPointsCategory ⥤ polySetValuesCategory := LeanCategories.Algebra.Poly.antiderivativesMethod.{0}
def antiderivativeRealization : FunctorRealization AntiderivativeExpr polyPointsCategory polySetValuesCategory antiderivativeDeclaration :=
  { sourceRealization := polyPointsRealization, targetRealization := polySetValuesRealization }
def degDeclaration : polyPointsCategory ⥤ degreesCategory := LeanCategories.Algebra.Poly.degreeMethod.{0}
def degRealization : FunctorRealization DegExpr polyPointsCategory degreesCategory degDeclaration :=
  { sourceRealization := polyPointsRealization, targetRealization := degreesRealization }
def companionDeclaration : polyPointsCategory ⥤ matrixSetValuesCategory := LeanCategories.Algebra.Poly.companionMethod.{0}
def companionRealization : FunctorRealization CompanionExpr polyPointsCategory matrixSetValuesCategory companionDeclaration :=
  { sourceRealization := polyPointsRealization, targetRealization := matrixSetValuesRealization }
def rootsDeclaration : domainPolyPointsCategory ⥤ rootValuesCategory := LeanCategories.Algebra.Poly.rootsMethod.{0}
def rootsRealization : FunctorRealization RootsExpr domainPolyPointsCategory rootValuesCategory rootsDeclaration :=
  { sourceRealization := domainPolyPointsRealization, targetRealization := rootValuesRealization }
def detDeclaration : matrixPointsCategory ⥤ ringValuesCategory := LeanCategories.Algebra.Mat.detMethod.{0}
def detRealization : FunctorRealization DetExpr matrixPointsCategory ringValuesCategory detDeclaration :=
  { sourceRealization := matrixPointsRealization, targetRealization := ringValuesRealization }
def traceDeclaration : matrixPointsCategory ⥤ ringValuesCategory := LeanCategories.Algebra.Mat.traceMethod.{0}
def traceRealization : FunctorRealization TraceExpr matrixPointsCategory ringValuesCategory traceDeclaration :=
  { sourceRealization := matrixPointsRealization, targetRealization := ringValuesRealization }
def charpolyDeclaration : matrixPointsCategory ⥤ polyValuesCategory := LeanCategories.Algebra.Mat.charpolyMethod.{0}
def charpolyRealization : FunctorRealization CharpolyExpr matrixPointsCategory polyValuesCategory charpolyDeclaration :=
  { sourceRealization := matrixPointsRealization, targetRealization := polyValuesRealization }
def inverseDeclaration : matrixPointsCategory ⥤ matrixSetValuesCategory := LeanCategories.Algebra.Mat.inverseMethod.{0}
def inverseRealization : FunctorRealization InverseExpr matrixPointsCategory matrixSetValuesCategory inverseDeclaration :=
  { sourceRealization := matrixPointsRealization, targetRealization := matrixSetValuesRealization }
def matrixRankDeclaration : matrixPointsCategory ⥤ naturalsCategory := LeanCategories.Algebra.Mat.rankMethod.{0}
def matrixRankRealization : FunctorRealization MatrixRankExpr matrixPointsCategory naturalsCategory matrixRankDeclaration :=
  { sourceRealization := matrixPointsRealization, targetRealization := naturalsRealization }
def matrixKerDeclaration : matrixPointsCategory ⥤ vectorSetValuesCategory := LeanCategories.Algebra.Mat.kernelMethod.{0}
def matrixKerRealization : FunctorRealization MatrixKerExpr matrixPointsCategory vectorSetValuesCategory matrixKerDeclaration :=
  { sourceRealization := matrixPointsRealization, targetRealization := vectorSetValuesRealization }
def unionDeclaration : CasCatalogue.Foundation.Subsets.coreSubobjectsSetsCategory.{0} ⥤ subsetOperationsCategory := LeanCategories.Foundation.subsetUnion.{0}
def unionRealization : FunctorRealization UnionExpr CasCatalogue.Foundation.Subsets.coreSubobjectsSetsCategory.{0} subsetOperationsCategory unionDeclaration :=
  { sourceRealization := CasCatalogue.Foundation.Subsets.coreSubobjectsSetsRealization, targetRealization := subsetOperationsRealization }
def intersectDeclaration : CasCatalogue.Foundation.Subsets.coreSubobjectsSetsCategory.{0} ⥤ subsetOperationsCategory := LeanCategories.Foundation.subsetInter.{0}
def intersectRealization : FunctorRealization IntersectExpr CasCatalogue.Foundation.Subsets.coreSubobjectsSetsCategory.{0} subsetOperationsCategory intersectDeclaration :=
  { sourceRealization := CasCatalogue.Foundation.Subsets.coreSubobjectsSetsRealization, targetRealization := subsetOperationsRealization }
def diffDeclaration : CasCatalogue.Foundation.Subsets.coreSubobjectsSetsCategory.{0} ⥤ subsetOperationsCategory := LeanCategories.Foundation.subsetDiff.{0}
def diffRealization : FunctorRealization DiffExpr CasCatalogue.Foundation.Subsets.coreSubobjectsSetsCategory.{0} subsetOperationsCategory diffDeclaration :=
  { sourceRealization := CasCatalogue.Foundation.Subsets.coreSubobjectsSetsRealization, targetRealization := subsetOperationsRealization }
def symdiffDeclaration : CasCatalogue.Foundation.Subsets.coreSubobjectsSetsCategory.{0} ⥤ subsetOperationsCategory := LeanCategories.Foundation.subsetSymmDiff.{0}
def symdiffRealization : FunctorRealization SymdiffExpr CasCatalogue.Foundation.Subsets.coreSubobjectsSetsCategory.{0} subsetOperationsCategory symdiffDeclaration :=
  { sourceRealization := CasCatalogue.Foundation.Subsets.coreSubobjectsSetsRealization, targetRealization := subsetOperationsRealization }
def subsetDeclaration : CasCatalogue.Foundation.Subsets.coreSubobjectsSetsCategory.{0} ⥤ CasCatalogue.Foundation.Subsets.subsetPredicatesCategory.{0} := LeanCategories.Foundation.subsetOf.{0}
def subsetRealization : FunctorRealization SubsetExpr CasCatalogue.Foundation.Subsets.coreSubobjectsSetsCategory.{0} CasCatalogue.Foundation.Subsets.subsetPredicatesCategory.{0} subsetDeclaration :=
  { sourceRealization := CasCatalogue.Foundation.Subsets.coreSubobjectsSetsRealization, targetRealization := CasCatalogue.Foundation.Subsets.subsetPredicatesCategoryRealization }
def nthDeclaration : enumerationsCategory ⥤ sequenceValuesCategory := LeanCategories.Foundation.nth.{0}
def nthRealization : FunctorRealization NthExpr enumerationsCategory sequenceValuesCategory nthDeclaration :=
  { sourceRealization := enumerationsRealization, targetRealization := sequenceValuesRealization }
def sumDeclaration : ringFiniteListsCategory ⥤ ringValuesCategory := LeanCategories.Foundation.finiteSum.{0}
def sumRealization : FunctorRealization SumExpr ringFiniteListsCategory ringValuesCategory sumDeclaration :=
  { sourceRealization := ringFiniteListsRealization, targetRealization := ringValuesRealization }
def prodDeclaration : ringFiniteListsCategory ⥤ ringValuesCategory := LeanCategories.Foundation.finiteProd.{0}
def prodRealization : FunctorRealization ProdExpr ringFiniteListsCategory ringValuesCategory prodDeclaration :=
  { sourceRealization := ringFiniteListsRealization, targetRealization := ringValuesRealization }
def multisetContainsDeclaration : multisetPointsCategory ⥤ pointPredicateValuesCategory := LeanCategories.Foundation.multisetContains.{0}
def multisetContainsRealization : FunctorRealization MultisetContainsExpr multisetPointsCategory pointPredicateValuesCategory multisetContainsDeclaration :=
  { sourceRealization := multisetPointsRealization, targetRealization := pointPredicateValuesRealization }
def multisetCardDeclaration : multisetPointsCategory ⥤ naturalsCategory := LeanCategories.Foundation.multisetCard.{0}
def multisetCardRealization : FunctorRealization MultisetCardExpr multisetPointsCategory naturalsCategory multisetCardDeclaration :=
  { sourceRealization := multisetPointsRealization, targetRealization := naturalsRealization }
def multisetEqualsDeclaration : multisetPointsCategory ⥤ subsetPredicateValuesCategory := LeanCategories.Foundation.multisetEquals.{0}
def multisetEqualsRealization : FunctorRealization MultisetEqualsExpr multisetPointsCategory subsetPredicateValuesCategory multisetEqualsDeclaration :=
  { sourceRealization := multisetPointsRealization, targetRealization := subsetPredicateValuesRealization }
def multisetSubsetDeclaration : multisetPointsCategory ⥤ subsetPredicateValuesCategory := LeanCategories.Foundation.multisetSubsetOf.{0}
def multisetSubsetRealization : FunctorRealization MultisetSubsetExpr multisetPointsCategory subsetPredicateValuesCategory multisetSubsetDeclaration :=
  { sourceRealization := multisetPointsRealization, targetRealization := subsetPredicateValuesRealization }
def reDeclaration : complexPointsCategory ⥤ realPointsCategory := LeanCategories.Analytic.re
def reRealization : FunctorRealization ReExpr complexPointsCategory realPointsCategory reDeclaration :=
  { sourceRealization := complexPointsRealization, targetRealization := realPointsRealization }
def imDeclaration : complexPointsCategory ⥤ realPointsCategory := LeanCategories.Analytic.im
def imRealization : FunctorRealization ImExpr complexPointsCategory realPointsCategory imDeclaration :=
  { sourceRealization := complexPointsRealization, targetRealization := realPointsRealization }
def barDeclaration : complexPointsCategory ⥤ complexPointsCategory := LeanCategories.Analytic.conj
def barRealization : FunctorRealization BarExpr complexPointsCategory complexPointsCategory barDeclaration :=
  { sourceRealization := complexPointsRealization, targetRealization := complexPointsRealization }
def absDeclaration : complexPointsCategory ⥤ realPointsCategory := LeanCategories.Analytic.abs
def absRealization : FunctorRealization AbsExpr complexPointsCategory realPointsCategory absDeclaration :=
  { sourceRealization := complexPointsRealization, targetRealization := realPointsRealization }
def approximateDeclaration : complexPointsCategory ⥤ approximationValuesCategory := LeanCategories.Analytic.approximations
def approximateRealization : FunctorRealization ApproximateExpr complexPointsCategory approximationValuesCategory approximateDeclaration :=
  { sourceRealization := complexPointsRealization, targetRealization := approximationValuesRealization }
def imageDeclaration : functionPointsCategory ⥤ CasCatalogue.Catalogue.ConstructorRegistration.subobjectsSetsCategory.{0} := LeanCategories.Analytic.image.{0}
def imageRealization : FunctorRealization ImageExpr functionPointsCategory CasCatalogue.Catalogue.ConstructorRegistration.subobjectsSetsCategory.{0} imageDeclaration :=
  { sourceRealization := functionPointsRealization, targetRealization := CasCatalogue.Catalogue.ConstructorRegistration.subobjectsSetsRealization }
def limitDeclaration : realFunctionPointsCategory ⥤ limitValuesCategory := LeanCategories.Analytic.limits
def limitRealization : FunctorRealization LimitExpr realFunctionPointsCategory limitValuesCategory limitDeclaration :=
  { sourceRealization := realFunctionPointsRealization, targetRealization := limitValuesRealization }
def integralDeclaration : realFunctionPointsCategory ⥤ integralValuesCategory := LeanCategories.Analytic.integral
def integralRealization : FunctorRealization IntegralExpr realFunctionPointsCategory integralValuesCategory integralDeclaration :=
  { sourceRealization := realFunctionPointsRealization, targetRealization := integralValuesRealization }
def taylorDeclaration : realFunctionPointsCategory ⥤ taylorValuesCategory := LeanCategories.Analytic.taylor
def taylorRealization : FunctorRealization TaylorExpr realFunctionPointsCategory taylorValuesCategory taylorDeclaration :=
  { sourceRealization := realFunctionPointsRealization, targetRealization := taylorValuesRealization }

end

end Elements

open Elements

normalized_registry .category
  { id := CategoryId.ringPoints, declaration := `CasCatalogue.Elements.ringPointsCategory
    expression := RingPoints, realization := `CasCatalogue.Elements.ringPointsRealization }
normalized_registry .category
  { id := CategoryId.ufdPoints, declaration := `CasCatalogue.Elements.ufdPointsCategory
    expression := UfdPoints, realization := `CasCatalogue.Elements.ufdPointsRealization }
normalized_registry .category
  { id := CategoryId.pidPoints, declaration := `CasCatalogue.Elements.pidPointsCategory
    expression := PidPoints, realization := `CasCatalogue.Elements.pidPointsRealization }
normalized_registry .category
  { id := CategoryId.euclideanPoints, declaration := `CasCatalogue.Elements.euclideanPointsCategory
    expression := EuclideanPoints, realization := `CasCatalogue.Elements.euclideanPointsRealization }
normalized_registry .category
  { id := CategoryId.polyPoints, declaration := `CasCatalogue.Elements.polyPointsCategory
    expression := PolyPoints, realization := `CasCatalogue.Elements.polyPointsRealization }
normalized_registry .category
  { id := CategoryId.domainPolyPoints, declaration := `CasCatalogue.Elements.domainPolyPointsCategory
    expression := DomainPolyPoints, realization := `CasCatalogue.Elements.domainPolyPointsRealization }
normalized_registry .category
  { id := CategoryId.ufdPolyPoints, declaration := `CasCatalogue.Elements.ufdPolyPointsCategory
    expression := UfdPolyPoints, realization := `CasCatalogue.Elements.ufdPolyPointsRealization }
normalized_registry .category
  { id := CategoryId.fieldPolyPoints, declaration := `CasCatalogue.Elements.fieldPolyPointsCategory
    expression := FieldPolyPoints, realization := `CasCatalogue.Elements.fieldPolyPointsRealization }
normalized_registry .category
  { id := CategoryId.matrixPoints, declaration := `CasCatalogue.Elements.matrixPointsCategory
    expression := MatrixPoints, realization := `CasCatalogue.Elements.matrixPointsRealization }
normalized_registry .category
  { id := CategoryId.enumerations, declaration := `CasCatalogue.Elements.enumerationsCategory
    expression := Enumerations, realization := `CasCatalogue.Elements.enumerationsRealization }
normalized_registry .category
  { id := CategoryId.finiteLists, declaration := `CasCatalogue.Elements.finiteListsCategory
    expression := FiniteLists, realization := `CasCatalogue.Elements.finiteListsRealization }
normalized_registry .category
  { id := CategoryId.ringFiniteLists, declaration := `CasCatalogue.Elements.ringFiniteListsCategory
    expression := RingFiniteLists, realization := `CasCatalogue.Elements.ringFiniteListsRealization }
normalized_registry .category
  { id := CategoryId.multisetPoints, declaration := `CasCatalogue.Elements.multisetPointsCategory
    expression := MultisetPoints, realization := `CasCatalogue.Elements.multisetPointsRealization }
normalized_registry .category
  { id := CategoryId.complexPoints, declaration := `CasCatalogue.Elements.complexPointsCategory
    expression := ComplexPoints, realization := `CasCatalogue.Elements.complexPointsRealization }
normalized_registry .category
  { id := CategoryId.realPoints, declaration := `CasCatalogue.Elements.realPointsCategory
    expression := RealPoints, realization := `CasCatalogue.Elements.realPointsRealization }
normalized_registry .category
  { id := CategoryId.functionPoints, declaration := `CasCatalogue.Elements.functionPointsCategory
    expression := FunctionPoints, realization := `CasCatalogue.Elements.functionPointsRealization }
normalized_registry .category
  { id := CategoryId.realFunctionPoints, declaration := `CasCatalogue.Elements.realFunctionPointsCategory
    expression := RealFunctionPoints, realization := `CasCatalogue.Elements.realFunctionPointsRealization }
normalized_registry .category
  { id := CategoryId.schemesOverQ, declaration := `CasCatalogue.Elements.schemesOverQCategory
    expression := SchemesOverQ, realization := `CasCatalogue.Elements.schemesOverQRealization }
normalized_registry .category
  { id := CategoryId.factorizations, declaration := `CasCatalogue.Elements.factorizationsCategory
    expression := Factorizations, realization := `CasCatalogue.Elements.factorizationsRealization }
normalized_registry .category
  { id := CategoryId.gcdValues, declaration := `CasCatalogue.Elements.gcdValuesCategory
    expression := GcdValues, realization := `CasCatalogue.Elements.gcdValuesRealization }
normalized_registry .category
  { id := CategoryId.propositions, declaration := `CasCatalogue.Elements.propositionsCategory
    expression := Propositions, realization := `CasCatalogue.Elements.propositionsRealization }
normalized_registry .category
  { id := CategoryId.polyValues, declaration := `CasCatalogue.Elements.polyValuesCategory
    expression := PolyValues, realization := `CasCatalogue.Elements.polyValuesRealization }
normalized_registry .category
  { id := CategoryId.polySetValues, declaration := `CasCatalogue.Elements.polySetValuesCategory
    expression := PolySetValues, realization := `CasCatalogue.Elements.polySetValuesRealization }
normalized_registry .category
  { id := CategoryId.degrees, declaration := `CasCatalogue.Elements.degreesCategory
    expression := Degrees, realization := `CasCatalogue.Elements.degreesRealization }
normalized_registry .category
  { id := CategoryId.matrixSetValues, declaration := `CasCatalogue.Elements.matrixSetValuesCategory
    expression := MatrixSetValues, realization := `CasCatalogue.Elements.matrixSetValuesRealization }
normalized_registry .category
  { id := CategoryId.rootValues, declaration := `CasCatalogue.Elements.rootValuesCategory
    expression := RootValues, realization := `CasCatalogue.Elements.rootValuesRealization }
normalized_registry .category
  { id := CategoryId.ringValues, declaration := `CasCatalogue.Elements.ringValuesCategory
    expression := RingValues, realization := `CasCatalogue.Elements.ringValuesRealization }
normalized_registry .category
  { id := CategoryId.naturals, declaration := `CasCatalogue.Elements.naturalsCategory
    expression := Naturals, realization := `CasCatalogue.Elements.naturalsRealization }
normalized_registry .category
  { id := CategoryId.vectorSetValues, declaration := `CasCatalogue.Elements.vectorSetValuesCategory
    expression := VectorSetValues, realization := `CasCatalogue.Elements.vectorSetValuesRealization }
normalized_registry .category
  { id := CategoryId.subsetOperations, declaration := `CasCatalogue.Elements.subsetOperationsCategory
    expression := SubsetOperations, realization := `CasCatalogue.Elements.subsetOperationsRealization }
normalized_registry .category
  { id := CategoryId.sequenceValues, declaration := `CasCatalogue.Elements.sequenceValuesCategory
    expression := SequenceValues, realization := `CasCatalogue.Elements.sequenceValuesRealization }
normalized_registry .category
  { id := CategoryId.pointPredicateValues, declaration := `CasCatalogue.Elements.pointPredicateValuesCategory
    expression := PointPredicateValues, realization := `CasCatalogue.Elements.pointPredicateValuesRealization }
normalized_registry .category
  { id := CategoryId.subsetPredicateValues, declaration := `CasCatalogue.Elements.subsetPredicateValuesCategory
    expression := SubsetPredicateValues, realization := `CasCatalogue.Elements.subsetPredicateValuesRealization }
normalized_registry .category
  { id := CategoryId.approximationValues, declaration := `CasCatalogue.Elements.approximationValuesCategory
    expression := ApproximationValues, realization := `CasCatalogue.Elements.approximationValuesRealization }
normalized_registry .category
  { id := CategoryId.limitValues, declaration := `CasCatalogue.Elements.limitValuesCategory
    expression := LimitValues, realization := `CasCatalogue.Elements.limitValuesRealization }
normalized_registry .category
  { id := CategoryId.integralValues, declaration := `CasCatalogue.Elements.integralValuesCategory
    expression := IntegralValues, realization := `CasCatalogue.Elements.integralValuesRealization }
normalized_registry .category
  { id := CategoryId.taylorValues, declaration := `CasCatalogue.Elements.taylorValuesCategory
    expression := TaylorValues, realization := `CasCatalogue.Elements.taylorValuesRealization }
normalized_registry .functor
  { id := FunctorId.euclideanToPid, source := EuclideanPoints, target := PidPoints
    declaration := `CasCatalogue.Elements.euclideanToPidDeclaration, realization := `CasCatalogue.Elements.euclideanToPidRealization
    expression := EuclideanToPidExpr, structural := true }
normalized_registry .functor
  { id := FunctorId.pidToUfd, source := PidPoints, target := UfdPoints
    declaration := `CasCatalogue.Elements.pidToUfdDeclaration, realization := `CasCatalogue.Elements.pidToUfdRealization
    expression := PidToUfdExpr, structural := true }
normalized_registry .functor
  { id := FunctorId.ufdToRing, source := UfdPoints, target := RingPoints
    declaration := `CasCatalogue.Elements.ufdToRingDeclaration, realization := `CasCatalogue.Elements.ufdToRingRealization
    expression := UfdToRingExpr, structural := true }
normalized_registry .functor
  { id := FunctorId.domainPolyToPoly, source := DomainPolyPoints, target := PolyPoints
    declaration := `CasCatalogue.Elements.domainPolyToPolyDeclaration, realization := `CasCatalogue.Elements.domainPolyToPolyRealization
    expression := DomainPolyToPolyExpr, structural := true }
normalized_registry .functor
  { id := FunctorId.ufdPolyToDomainPoly, source := UfdPolyPoints, target := DomainPolyPoints
    declaration := `CasCatalogue.Elements.ufdPolyToDomainPolyDeclaration, realization := `CasCatalogue.Elements.ufdPolyToDomainPolyRealization
    expression := UfdPolyToDomainPolyExpr, structural := true }
normalized_registry .functor
  { id := FunctorId.ufdPolyToUfd, source := UfdPolyPoints, target := UfdPoints
    declaration := `CasCatalogue.Elements.ufdPolyToUfdDeclaration, realization := `CasCatalogue.Elements.ufdPolyToUfdRealization
    expression := UfdPolyToUfdExpr, structural := true }
normalized_registry .functor
  { id := FunctorId.fieldPolyToDomainPoly, source := FieldPolyPoints, target := DomainPolyPoints
    declaration := `CasCatalogue.Elements.fieldPolyToDomainPolyDeclaration, realization := `CasCatalogue.Elements.fieldPolyToDomainPolyRealization
    expression := FieldPolyToDomainPolyExpr, structural := true }
normalized_registry .functor
  { id := FunctorId.fieldPolyToEuclidean, source := FieldPolyPoints, target := EuclideanPoints
    declaration := `CasCatalogue.Elements.fieldPolyToEuclideanDeclaration, realization := `CasCatalogue.Elements.fieldPolyToEuclideanRealization
    expression := FieldPolyToEuclideanExpr, structural := true }
normalized_registry .functor
  { id := FunctorId.finiteListsToEnumerations, source := FiniteLists, target := Enumerations
    declaration := `CasCatalogue.Elements.finiteListsToEnumerationsDeclaration, realization := `CasCatalogue.Elements.finiteListsToEnumerationsRealization
    expression := FiniteListsToEnumerationsExpr, structural := true }
normalized_registry .functor
  { id := FunctorId.enumerationsToSubsets, source := Enumerations, target := Constructed.SubobjectsSets
    declaration := `CasCatalogue.Elements.enumerationsToSubsetsDeclaration, realization := `CasCatalogue.Elements.enumerationsToSubsetsRealization
    expression := EnumerationsToSubsetsExpr, structural := true }
normalized_registry .functor
  { id := FunctorId.ringFiniteListsForget, source := RingFiniteLists, target := FiniteLists
    declaration := `CasCatalogue.Elements.ringFiniteListsForgetDeclaration, realization := `CasCatalogue.Elements.ringFiniteListsForgetRealization
    expression := RingFiniteListsForgetExpr, structural := true }
normalized_registry .functor
  { id := FunctorId.realToComplex, source := RealPoints, target := ComplexPoints
    declaration := `CasCatalogue.Elements.realToComplexDeclaration, realization := `CasCatalogue.Elements.realToComplexRealization
    expression := RealToComplexExpr, structural := true }
normalized_registry .functor
  { id := FunctorId.realFunctionToFunction, source := RealFunctionPoints, target := FunctionPoints
    declaration := `CasCatalogue.Elements.realFunctionToFunctionDeclaration, realization := `CasCatalogue.Elements.realFunctionToFunctionRealization
    expression := RealFunctionToFunctionExpr, structural := true }
normalized_registry .functor
  { id := FunctorId.factor, source := UfdPoints, target := Factorizations
    declaration := `CasCatalogue.Elements.factorDeclaration, realization := `CasCatalogue.Elements.factorRealization
    expression := FactorExpr }
normalized_registry .functor
  { id := FunctorId.gcd, source := UfdPoints, target := GcdValues
    declaration := `CasCatalogue.Elements.gcdDeclaration, realization := `CasCatalogue.Elements.gcdRealization
    expression := GcdExpr }
normalized_registry .functor
  { id := FunctorId.isPrime, source := UfdPoints, target := Propositions
    declaration := `CasCatalogue.Elements.isPrimeDeclaration, realization := `CasCatalogue.Elements.isPrimeRealization
    expression := IsPrimeExpr }
normalized_registry .functor
  { id := FunctorId.derivative, source := PolyPoints, target := PolyValues
    declaration := `CasCatalogue.Elements.derivativeDeclaration, realization := `CasCatalogue.Elements.derivativeRealization
    expression := DerivativeExpr }
normalized_registry .functor
  { id := FunctorId.antiderivative, source := PolyPoints, target := PolySetValues
    declaration := `CasCatalogue.Elements.antiderivativeDeclaration, realization := `CasCatalogue.Elements.antiderivativeRealization
    expression := AntiderivativeExpr }
normalized_registry .functor
  { id := FunctorId.deg, source := PolyPoints, target := Degrees
    declaration := `CasCatalogue.Elements.degDeclaration, realization := `CasCatalogue.Elements.degRealization
    expression := DegExpr }
normalized_registry .functor
  { id := FunctorId.companion, source := PolyPoints, target := MatrixSetValues
    declaration := `CasCatalogue.Elements.companionDeclaration, realization := `CasCatalogue.Elements.companionRealization
    expression := CompanionExpr }
normalized_registry .functor
  { id := FunctorId.roots, source := DomainPolyPoints, target := RootValues
    declaration := `CasCatalogue.Elements.rootsDeclaration, realization := `CasCatalogue.Elements.rootsRealization
    expression := RootsExpr }
normalized_registry .functor
  { id := FunctorId.det, source := MatrixPoints, target := RingValues
    declaration := `CasCatalogue.Elements.detDeclaration, realization := `CasCatalogue.Elements.detRealization
    expression := DetExpr }
normalized_registry .functor
  { id := FunctorId.trace, source := MatrixPoints, target := RingValues
    declaration := `CasCatalogue.Elements.traceDeclaration, realization := `CasCatalogue.Elements.traceRealization
    expression := TraceExpr }
normalized_registry .functor
  { id := FunctorId.charpoly, source := MatrixPoints, target := PolyValues
    declaration := `CasCatalogue.Elements.charpolyDeclaration, realization := `CasCatalogue.Elements.charpolyRealization
    expression := CharpolyExpr }
normalized_registry .functor
  { id := FunctorId.inverse, source := MatrixPoints, target := MatrixSetValues
    declaration := `CasCatalogue.Elements.inverseDeclaration, realization := `CasCatalogue.Elements.inverseRealization
    expression := InverseExpr }
normalized_registry .functor
  { id := FunctorId.matrixRank, source := MatrixPoints, target := Naturals
    declaration := `CasCatalogue.Elements.matrixRankDeclaration, realization := `CasCatalogue.Elements.matrixRankRealization
    expression := MatrixRankExpr }
normalized_registry .functor
  { id := FunctorId.matrixKer, source := MatrixPoints, target := VectorSetValues
    declaration := `CasCatalogue.Elements.matrixKerDeclaration, realization := `CasCatalogue.Elements.matrixKerRealization
    expression := MatrixKerExpr }
normalized_registry .functor
  { id := FunctorId.union, source := Foundation.Subsets.CoreSubobjectsSets, target := SubsetOperations
    declaration := `CasCatalogue.Elements.unionDeclaration, realization := `CasCatalogue.Elements.unionRealization
    expression := UnionExpr }
normalized_registry .functor
  { id := FunctorId.intersect, source := Foundation.Subsets.CoreSubobjectsSets, target := SubsetOperations
    declaration := `CasCatalogue.Elements.intersectDeclaration, realization := `CasCatalogue.Elements.intersectRealization
    expression := IntersectExpr }
normalized_registry .functor
  { id := FunctorId.diff, source := Foundation.Subsets.CoreSubobjectsSets, target := SubsetOperations
    declaration := `CasCatalogue.Elements.diffDeclaration, realization := `CasCatalogue.Elements.diffRealization
    expression := DiffExpr }
normalized_registry .functor
  { id := FunctorId.symdiff, source := Foundation.Subsets.CoreSubobjectsSets, target := SubsetOperations
    declaration := `CasCatalogue.Elements.symdiffDeclaration, realization := `CasCatalogue.Elements.symdiffRealization
    expression := SymdiffExpr }
normalized_registry .functor
  { id := FunctorId.subset, source := Foundation.Subsets.CoreSubobjectsSets, target := Foundation.Subsets.SubsetPredicates
    declaration := `CasCatalogue.Elements.subsetDeclaration, realization := `CasCatalogue.Elements.subsetRealization
    expression := SubsetExpr }
normalized_registry .functor
  { id := FunctorId.nth, source := Enumerations, target := SequenceValues
    declaration := `CasCatalogue.Elements.nthDeclaration, realization := `CasCatalogue.Elements.nthRealization
    expression := NthExpr }
normalized_registry .functor
  { id := FunctorId.sum, source := RingFiniteLists, target := RingValues
    declaration := `CasCatalogue.Elements.sumDeclaration, realization := `CasCatalogue.Elements.sumRealization
    expression := SumExpr }
normalized_registry .functor
  { id := FunctorId.prod, source := RingFiniteLists, target := RingValues
    declaration := `CasCatalogue.Elements.prodDeclaration, realization := `CasCatalogue.Elements.prodRealization
    expression := ProdExpr }
normalized_registry .functor
  { id := FunctorId.multisetContains, source := MultisetPoints, target := PointPredicateValues
    declaration := `CasCatalogue.Elements.multisetContainsDeclaration, realization := `CasCatalogue.Elements.multisetContainsRealization
    expression := MultisetContainsExpr }
normalized_registry .functor
  { id := FunctorId.multisetCard, source := MultisetPoints, target := Naturals
    declaration := `CasCatalogue.Elements.multisetCardDeclaration, realization := `CasCatalogue.Elements.multisetCardRealization
    expression := MultisetCardExpr }
normalized_registry .functor
  { id := FunctorId.multisetEquals, source := MultisetPoints, target := SubsetPredicateValues
    declaration := `CasCatalogue.Elements.multisetEqualsDeclaration, realization := `CasCatalogue.Elements.multisetEqualsRealization
    expression := MultisetEqualsExpr }
normalized_registry .functor
  { id := FunctorId.multisetSubset, source := MultisetPoints, target := SubsetPredicateValues
    declaration := `CasCatalogue.Elements.multisetSubsetDeclaration, realization := `CasCatalogue.Elements.multisetSubsetRealization
    expression := MultisetSubsetExpr }
normalized_registry .functor
  { id := FunctorId.re, source := ComplexPoints, target := RealPoints
    declaration := `CasCatalogue.Elements.reDeclaration, realization := `CasCatalogue.Elements.reRealization
    expression := ReExpr }
normalized_registry .functor
  { id := FunctorId.im, source := ComplexPoints, target := RealPoints
    declaration := `CasCatalogue.Elements.imDeclaration, realization := `CasCatalogue.Elements.imRealization
    expression := ImExpr }
normalized_registry .functor
  { id := FunctorId.bar, source := ComplexPoints, target := ComplexPoints
    declaration := `CasCatalogue.Elements.barDeclaration, realization := `CasCatalogue.Elements.barRealization
    expression := BarExpr }
normalized_registry .functor
  { id := FunctorId.abs, source := ComplexPoints, target := RealPoints
    declaration := `CasCatalogue.Elements.absDeclaration, realization := `CasCatalogue.Elements.absRealization
    expression := AbsExpr }
normalized_registry .functor
  { id := FunctorId.approximate, source := ComplexPoints, target := ApproximationValues
    declaration := `CasCatalogue.Elements.approximateDeclaration, realization := `CasCatalogue.Elements.approximateRealization
    expression := ApproximateExpr }
normalized_registry .functor
  { id := FunctorId.image, source := FunctionPoints, target := Constructed.SubobjectsSets
    declaration := `CasCatalogue.Elements.imageDeclaration, realization := `CasCatalogue.Elements.imageRealization
    expression := ImageExpr }
normalized_registry .functor
  { id := FunctorId.limit, source := RealFunctionPoints, target := LimitValues
    declaration := `CasCatalogue.Elements.limitDeclaration, realization := `CasCatalogue.Elements.limitRealization
    expression := LimitExpr }
normalized_registry .functor
  { id := FunctorId.integral, source := RealFunctionPoints, target := IntegralValues
    declaration := `CasCatalogue.Elements.integralDeclaration, realization := `CasCatalogue.Elements.integralRealization
    expression := IntegralExpr }
normalized_registry .functor
  { id := FunctorId.taylor, source := RealFunctionPoints, target := TaylorValues
    declaration := `CasCatalogue.Elements.taylorDeclaration, realization := `CasCatalogue.Elements.taylorRealization
    expression := TaylorExpr }
normalized_registry .method
  { id := ⟨"meth.factor"⟩, name := "factor", owner := UfdPoints
    functor := FunctorId.factor, shape := .object }
normalized_registry .method
  { id := ⟨"meth.gcd"⟩, name := "gcd", owner := UfdPoints
    functor := FunctorId.gcd, shape := .object }
normalized_registry .method
  { id := ⟨"meth.is_prime"⟩, name := "is_prime", owner := UfdPoints
    functor := FunctorId.isPrime, shape := .object }
normalized_registry .method
  { id := ⟨"meth.derivative"⟩, name := "derivative", owner := PolyPoints
    functor := FunctorId.derivative, shape := .object }
normalized_registry .method
  { id := ⟨"meth.antiderivative"⟩, name := "antiderivative", owner := PolyPoints
    functor := FunctorId.antiderivative, shape := .object }
normalized_registry .method
  { id := ⟨"meth.deg"⟩, name := "deg", owner := PolyPoints
    functor := FunctorId.deg, shape := .object }
normalized_registry .method
  { id := ⟨"meth.companion_matrix"⟩, name := "companion_matrix", owner := PolyPoints
    functor := FunctorId.companion, shape := .object }
normalized_registry .method
  { id := ⟨"meth.roots"⟩, name := "roots", owner := DomainPolyPoints
    functor := FunctorId.roots, shape := .object }
normalized_registry .method
  { id := ⟨"meth.det"⟩, name := "det", owner := MatrixPoints
    functor := FunctorId.det, shape := .object }
normalized_registry .method
  { id := ⟨"meth.trace"⟩, name := "trace", owner := MatrixPoints
    functor := FunctorId.trace, shape := .object }
normalized_registry .method
  { id := ⟨"meth.charpoly"⟩, name := "charpoly", owner := MatrixPoints
    functor := FunctorId.charpoly, shape := .object }
normalized_registry .method
  { id := ⟨"meth.inverse"⟩, name := "inverse", owner := MatrixPoints
    functor := FunctorId.inverse, shape := .object }
normalized_registry .method
  { id := ⟨"meth.matrix_rank"⟩, name := "rank", owner := MatrixPoints
    functor := FunctorId.matrixRank, shape := .object }
normalized_registry .method
  { id := ⟨"meth.matrix_ker"⟩, name := "ker", owner := MatrixPoints
    functor := FunctorId.matrixKer, shape := .object }
normalized_registry .method
  { id := ⟨"meth.union"⟩, name := "union", owner := Constructed.SubobjectsSets
    functor := FunctorId.union, shape := .isoInvariant }
normalized_registry .method
  { id := ⟨"meth.intersect"⟩, name := "intersect", owner := Constructed.SubobjectsSets
    functor := FunctorId.intersect, shape := .isoInvariant }
normalized_registry .method
  { id := ⟨"meth.diff"⟩, name := "diff", owner := Constructed.SubobjectsSets
    functor := FunctorId.diff, shape := .isoInvariant }
normalized_registry .method
  { id := ⟨"meth.symdiff"⟩, name := "symdiff", owner := Constructed.SubobjectsSets
    functor := FunctorId.symdiff, shape := .isoInvariant }
normalized_registry .method
  { id := ⟨"meth.subset"⟩, name := "subset", owner := Constructed.SubobjectsSets
    functor := FunctorId.subset, shape := .isoInvariant }
normalized_registry .method
  { id := ⟨"meth.nth"⟩, name := "nth", owner := Enumerations
    functor := FunctorId.nth, shape := .object }
normalized_registry .method
  { id := ⟨"meth.sum"⟩, name := "sum", owner := RingFiniteLists
    functor := FunctorId.sum, shape := .object }
normalized_registry .method
  { id := ⟨"meth.prod"⟩, name := "prod", owner := RingFiniteLists
    functor := FunctorId.prod, shape := .object }
normalized_registry .method
  { id := ⟨"meth.multiset_contains"⟩, name := "contains", owner := MultisetPoints
    functor := FunctorId.multisetContains, shape := .object }
normalized_registry .method
  { id := ⟨"meth.multiset_cardinality"⟩, name := "cardinality", owner := MultisetPoints
    functor := FunctorId.multisetCard, shape := .object }
normalized_registry .method
  { id := ⟨"meth.multiset_set_eq"⟩, name := "set_eq", owner := MultisetPoints
    functor := FunctorId.multisetEquals, shape := .object }
normalized_registry .method
  { id := ⟨"meth.multiset_subset"⟩, name := "subset", owner := MultisetPoints
    functor := FunctorId.multisetSubset, shape := .object }
normalized_registry .method
  { id := ⟨"meth.complex_re"⟩, name := "re", owner := ComplexPoints
    functor := FunctorId.re, shape := .object }
normalized_registry .method
  { id := ⟨"meth.complex_im"⟩, name := "im", owner := ComplexPoints
    functor := FunctorId.im, shape := .object }
normalized_registry .method
  { id := ⟨"meth.bar"⟩, name := "bar", owner := ComplexPoints
    functor := FunctorId.bar, shape := .object }
normalized_registry .method
  { id := ⟨"meth.abs"⟩, name := "abs", owner := ComplexPoints
    functor := FunctorId.abs, shape := .object }
normalized_registry .method
  { id := ⟨"meth.approximate"⟩, name := "approximate", owner := ComplexPoints
    functor := FunctorId.approximate, shape := .object }
normalized_registry .method
  { id := ⟨"meth.image"⟩, name := "image", owner := FunctionPoints
    functor := FunctorId.image, shape := .object }
normalized_registry .method
  { id := ⟨"meth.limit"⟩, name := "limit", owner := RealFunctionPoints
    functor := FunctorId.limit, shape := .object }
normalized_registry .method
  { id := ⟨"meth.definite_integral"⟩, name := "definite_integral", owner := RealFunctionPoints
    functor := FunctorId.integral, shape := .object }
normalized_registry .method
  { id := ⟨"meth.taylor_expansion"⟩, name := "taylor_expansion", owner := RealFunctionPoints
    functor := FunctorId.taylor, shape := .object }

end CasCatalogue
