/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import CasAcceptance.Standard
public import CasCatalogue.ResolveSyntax
public import CasLeaves.Modules.Bilinear.Valued.WForms
public import Mathlib.Tactic.Ring
public import Mathlib.Tactic.FinCases
public import Mathlib.Tactic.NormNum
public meta import CasAcceptance.Standard
public meta import CasCatalogue.ResolveSyntax
public meta import CasLeaves.Modules.Bilinear.Valued.WForms

@[expose] public section

/-!
# Acceptance for `cc-forms-general`: the discriminant of `A₂` is a registered cokernel

`L = (ℤ², G)` with `G = [[2, -1], [-1, 2]]` and `L♯ = (ℤ², G⁻¹)` with rational values, in dual
coordinates, and `L → L♯` is `x ↦ G x` on carriers and `ℤ ⊆ ℚ` on values. The discriminant is the
registered cokernel `colim.bil_w_form.cokernel` of that map in formed modules with varying values:
its apex is presented by the leaf, its coprojection from `L♯` is the core's. Its carrier is
`ℤ/3`, generated by the class of `e₁` (`3 e₁ = G (2, 1)`, `e₁ ∉ G ℤ²`, `e₂ ≡ 2 e₁`), and the
value `b([e₁], [e₁])` is the class of `2/3`.
-/

open CategoryTheory Limits
open LeanCategories.Modules.Bilinear.Valued
open CasCatalogue.Modules.Bilinear.Valued.WForms

namespace CasCatalogue.DiscriminantProbes

abbrev G : Fin 2 → Fin 2 → ℤ := ![![2, -1], ![-1, 2]]

abbrev A2 : FreeWForm := ⟨2, .int, G⟩
abbrev A2dual : FreeWForm := ⟨2, .rat, ![![2 / 3, 1 / 3], ![1 / 3, 2 / 3]]⟩

/-- `L → L♯`. -/
def toDual : FreeHom A2 A2dual where
  matrix := G
  cast := Int.castRingHom ℚ
  cast_eq := rfl
  preserves x y := by
    change ((∑ i, ∑ j, ((x i * y j : ℤ) : ℤ) * G i j : ℤ) : ℚ) =
      ∑ i, ∑ j, (((∑ k, G i k * x k) * (∑ k, G j k * y k) : ℤ) : ℚ) * A2dual.gram i j
    simp [Fin.sum_univ_two, A2dual]
    ring

noncomputable abbrev D : WalkingParallelPair ⥤ WFormHandles :=
  parallelPair toDual.handle (InducedCategory.homMk 0)

/-- The registered cokernel, on the diagram's denotation. -/
noncomputable def L : ColimitCocone (D ⋙ wformDenotation) := by
  exact colimitCoconeOfIso (diagramIsoParallelPair _)
    (Limits.Registration.bilWFormCokernel toDual.toHom)

noncomputable def apex := cokernelApex A2 A2dual toDual

/-- The discriminant, as a colimit cocone of handles. -/
noncomputable def P : ColimitCocone D :=
  realizedColimitCocone wformDenotationFullyFaithful L apex.1 apex.2

/- The apex is the cokernel of `L → L♯`, presented. -/
#guard match (exec% P.cocone.pt : WFormHandle) with
  | .cokernel a b _ => a.rank == 2 && a.values == .int && b.values == .rat
  | _ => false

/- The representative of `b([e₁], [e₁])`: `2/3`. -/
#guard A2dual.bilin (Pi.single 0 1) (Pi.single 0 1) == (2 / 3 : ℚ)

/-- The class of a vector of `L♯` in the discriminant. -/
noncomputable abbrev cls (v : Fin 2 → ℤ) : BilWFormCat.CokernelCarrier toDual.toHom :=
  BilWFormCat.cokernelCarrierProjection toDual.toHom v

abbrev e₁ : Fin 2 → ℤ := ![1, 0]
abbrev e₂ : Fin 2 → ℤ := ![0, 1]

/-- `v ≡ w` in the discriminant iff `v - w ∈ G ℤ²`. -/
theorem cls_eq_iff (v w : Fin 2 → ℤ) :
    cls v = cls w ↔ ∃ x : Fin 2 → ℤ, toDual.carrier x = v - w := by
  change Submodule.Quotient.mk (p := BilWFormCat.cokernelCarrierRelations toDual.toHom) v =
    Submodule.Quotient.mk w ↔ _
  exact (Submodule.Quotient.eq _).trans Iff.rfl

theorem three_e₁ : 3 • cls e₁ = 0 := by
  rw [show (3 • cls e₁ : BilWFormCat.CokernelCarrier toDual.toHom) = cls (3 • e₁) from
    (map_nsmul _ _ _).symm, show (0 : BilWFormCat.CokernelCarrier toDual.toHom) = cls 0 from
    (map_zero _).symm, cls_eq_iff]
  refine ⟨![2, 1], ?_⟩
  funext i; fin_cases i <;> rfl

theorem e₁_ne_zero : cls e₁ ≠ 0 := by
  rw [show (0 : BilWFormCat.CokernelCarrier toDual.toHom) = cls 0 from (map_zero _).symm, Ne,
    cls_eq_iff]
  rintro ⟨x, hx⟩
  have h0 := congrFun hx 0
  have h1 := congrFun hx 1
  change (∑ k, G 0 k * x k) = (e₁ - 0) 0 at h0
  change (∑ k, G 1 k * x k) = (e₁ - 0) 1 at h1
  simp [Fin.sum_univ_two] at h0 h1
  omega

theorem e₂_eq : cls e₂ = 2 • cls e₁ := by
  rw [show (2 • cls e₁ : BilWFormCat.CokernelCarrier toDual.toHom) = cls (2 • e₁) from
    (map_nsmul _ _ _).symm, cls_eq_iff]
  refine ⟨![-1, 0], ?_⟩
  funext i; fin_cases i <;> rfl

/-- The form on the discriminant: `b([e₁], [e₁])` is the class of `2/3`. -/
theorem pairing_e₁ :
    BilWFormCat.cokernelBilinMap toDual.toHom (cls e₁) (cls e₁) =
      BilWFormCat.cokernelValueProjection toDual.toHom (2 / 3 : ℚ) := by
  change BilWFormCat.cokernelValueProjection toDual.toHom (A2dual.bilin e₁ e₁) = _
  congr 1
  change (∑ i, ∑ j, ((e₁ i * e₁ j : ℤ) : ℚ) * A2dual.gram i j) = 2 / 3
  simp [Fin.sum_univ_two, e₁]

/-- The integers, as `ℤ`-linear values in `ℚ`. -/
noncomputable abbrev integers : Submodule ℤ ℚ :=
  LinearMap.range (Int.castRingHom ℚ).toIntAlgHom.toLinearMap

/-- A mixed pairing `b♯(G x, y) = xᵀ y` is an integer. -/
theorem mixed_integral (x y : Fin 2 → ℤ) :
    A2dual.bilin (toDual.carrier x) y = ((x 0 * y 0 + x 1 * y 1 : ℤ) : ℚ) := by
  change (∑ i, ∑ j, (((∑ k, G i k * x k) * y j : ℤ) : ℚ) * A2dual.gram i j) = _
  simp [Fin.sum_univ_two, A2dual]
  ring

/-- `b♯(y, G x) = xᵀ y`. -/
theorem mixed_integral' (x y : Fin 2 → ℤ) :
    A2dual.bilin y (toDual.carrier x) = ((x 0 * y 0 + x 1 * y 1 : ℤ) : ℚ) := by
  change (∑ i, ∑ j, ((y i * (∑ k, G j k * x k) : ℤ) : ℚ) * A2dual.gram i j) = _
  simp [Fin.sum_univ_two, A2dual]
  ring

/-- The value relations of the discriminant are the integers. -/
theorem valueRelations_le : BilWFormCat.cokernelValueRelations toDual.toHom ≤ integers := by
  refine sup_le (sup_le ?_ ?_) ?_
  · rintro _ ⟨n, rfl⟩
    exact ⟨n, rfl⟩
  · refine Submodule.span_le.mpr ?_
    rintro _ ⟨⟨(x : Fin 2 → ℤ), (y : Fin 2 → ℤ)⟩, rfl⟩
    exact ⟨x 0 * y 0 + x 1 * y 1, (mixed_integral x y).symm⟩
  · refine Submodule.span_le.mpr ?_
    rintro _ ⟨⟨(y : Fin 2 → ℤ), (x : Fin 2 → ℤ)⟩, rfl⟩
    exact ⟨x 0 * y 0 + x 1 * y 1, (mixed_integral' x y).symm⟩

/-- `1` is a relation, and `2/3` is not: `b([e₁], [e₁]) = 2/3 mod 1`, nonzero. -/
theorem one_rel : BilWFormCat.cokernelValueProjection toDual.toHom (1 : ℚ) = 0 :=
  (Submodule.Quotient.mk_eq_zero _).mpr
    (Submodule.mem_sup_left (Submodule.mem_sup_left ⟨(1 : ℤ), (Int.cast_one : ((1 : ℤ) : ℚ) = 1)⟩))

theorem two_thirds_ne : BilWFormCat.cokernelValueProjection toDual.toHom (2 / 3 : ℚ) ≠ 0 := by
  intro h
  obtain ⟨n, hn⟩ := valueRelations_le ((Submodule.Quotient.mk_eq_zero _).mp h)
  have : (3 * n : ℚ) = 2 := by
    change ((n : ℤ) : ℚ) = 2 / 3 at hn
    rw [hn]; norm_num
  have : 3 * n = 2 := by exact_mod_cast this
  omega

/-- The coprojection `L♯ → L♯/L` realized by the core is lean-categories' quotient map. -/
theorem coprojection : wformDenotation.map (P.cocone.ι.app .one) =
    BilWFormCat.cokernelProjection toDual.toHom := by
  rw [show wformDenotation.map (P.cocone.ι.app .one) = _ from
    realizedColimitCocone_leg wformDenotationFullyFaithful L apex.1 apex.2 .one]
  simp only [L, colimitCoconeOfIso, apex, cokernelApex, Iso.refl_inv]
  rfl

/-- A cocone descends through the discriminant uniquely. -/
theorem descends (s : Cocone D) (m : P.cocone.pt ⟶ s.pt)
    (h : ∀ j, P.cocone.ι.app j ≫ m = s.ι.app j) : m = P.isColimit.desc s :=
  P.isColimit.uniq s m h

end CasCatalogue.DiscriminantProbes
