/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import CasAcceptance.PropsProbes
public meta import CasAcceptance.PropsProbes

@[expose] public section

/-!
# Acceptance for `cc-universal` (CC-UNIV)

A hostile backend returns "the subgroup of `S₃` generated by `r`" as an unclosed generator list,
a false claim that it is not abelian, and a method inventory. `decode` turns it into a
realization of the semantic subgroup — the monomorphism `A₃ ↪ S₃` — and then:

* the user's `H` has every generic subgroup operation, with no forwarding wrapper: `cardinality`
  and `is_commutative` through the structural domain functor, `inclusion` as the retained arrow;
  intersection and inverse image are Mathlib's `Subobject` lattice and pullback;
* `H.inclusion` is the semantic inclusion (a theorem, by the action's denotation);
* the backend's label is ignored: `A₃` is decided abelian;
* a realization without the inclusion cannot stand in for the subobject: a decoder returning only
  the subgroup's table does not have the decoder's type, and an action on bare groups is rejected
  as a realization of the domain functor.
-/

open CategoryTheory Lean Meta Elab Command
open CasCatalogue.Algebra.Actions CasCatalogue.Algebra.Subgroups CasCatalogue.PropsProbes
open CasCatalogue.Foundation.Cardinality

namespace CasCatalogue.UnivProbes

/-- The backend's answer for `⟨r⟩ ≤ S₃`. -/
def hostileA3 : HostileSubgroup :=
  { ambient := s3, generators := [⟨1, by decide⟩], claimsAbelian := false
    methodNames := ["order", "IsAbelian", "is_normal", "kernel", "AsSubgroup"] }

/-- The backend's answer for `S₃` itself, from two generators. -/
def hostileS3 : HostileSubgroup :=
  { ambient := s3, generators := [⟨1, by decide⟩, ⟨3, by decide⟩], claimsAbelian := true
    methodNames := [] }

/-- The decoded subgroup `A₃ ↪ S₃`. -/
def a3 : SubgroupHandle := (decode hostileA3).get (by decide)

/-- The decoded `S₃ ↪ S₃`. -/
def s3sub : SubgroupHandle := (decode hostileS3).get (by decide)

/- Generic subgroup operations, inherited through the domain functor. -/
#guard method% cardinality (a3) in "cat.subobjects_groups" == CardinalHandle.finite 3
#guard method% cardinality (s3sub) in "cat.subobjects_groups" == CardinalHandle.finite 6
/- The backend's labels are ignored; the property is decided. -/
#guard (ask% is_commutative (a3) in "cat.subobjects_groups").answer == some true
#guard (ask% is_commutative (s3sub) in "cat.subobjects_groups").answer == some false
/- The inclusion is the retained embedding: `A₃ = {1, r, r²}` inside `S₃`. -/
#guard ((List.ofFn (method% inclusion (a3) in "cat.subobjects_groups").map).map (·.val)).mergeSort
  == [0, 1, 2]

/-- `H.inclusion` denotes the semantic inclusion of the subobject `H`. -/
theorem inclusion_is_semantic (H : SubgroupHandle) :
    arrowDenotation.obj (inclusionAction.obj H) =
      inclusionDeclaration.obj (subgroupDenotation.obj H) :=
  inclusionAction.obj_denote H

/-- The subobject a subgroup handle denotes, in Mathlib's `Subobject` lattice. -/
noncomputable def asSubobject (H : SubgroupHandle) : Subobject (GrpCat.of H.target.Carrier) :=
  haveI := H.mono
  Subobject.mk (GrpCat.ofHom H.toHomHandle.hom)

/-- Intersection of subgroups is Mathlib's meet of subobjects (pullbacks in `Grp`). -/
noncomputable def intersection {G : GrpCat.{0}} (H K : Subobject G) : Subobject G := H ⊓ K

/-- Inverse image along a homomorphism is Mathlib's pullback of subobjects. -/
noncomputable def inverseImage {G G' : GrpCat.{0}} (f : G' ⟶ G) (H : Subobject G) :
    Subobject G' :=
  (Subobject.pullback f).obj H

/-- A decoder that keeps only the subgroup's table, dropping its inclusion. -/
def apexOnlyDecode (h : HostileSubgroup) : Option GroupTable := (decode h).map (·.source)

/- It is not a subgroup decoder: the decoder's type demands the embedding. -/
example : True := by
  fail_if_success
    let _decoder : HostileSubgroup → Option SubgroupHandle := apexOnlyDecode
  trivial

run_cmd liftTermElabM do
  let rejects (entry : RegistryEntry) : MetaM Bool := do
    try validateRegistryEntryDeclaration entry; pure false
    catch _ => pure true
  -- An action on bare groups cannot realize the subobject's domain functor.
  unless ← rejects (.action
      { id := ⟨"act.probe.apex_only"⟩, edge := .functor FunctorId.subobjectsGroupsDomain
        realization := ``groupToMonoid }) do
    throwError "an apex-only action was accepted for subobjects"
  -- The registered subobject actions re-validate.
  if ← rejects (.action
      { id := ⟨"act.probe.control"⟩, edge := .functor FunctorId.subobjectsGroupsInclusion
        realization := ``inclusionAction }) then
    throwError "the inclusion action was rejected"

end CasCatalogue.UnivProbes
